import Day1
import Day2
import Day3
import Day4
import Day5
import Day6
import Day7
import Day8
import Day9
import Day10
import Day11
import Day12

# Day1.Day1_first_half()
# Day1.Day1_second_half()
# Day2.Day2_first_half()
# Day2.Day2_second_half()
# Day3.Day3_first_half()
# Day3.Day3_second_half()
# Day4.Day4_first_half()
# Day4.Day4_second_half(False)
# Day5.Day5_first_half()
# Day5.Day5_second_half()
# Day6.Day6_first_half()
# Day6.Day6_second_half()
# Day7.day7_first_half(True)
# Day8.Day8_first_half()
# Day8.Day8_second_half()
# Day9.Day9_second_half()
# Day10.Day10_first_half()
# Day10.Day10_second_half()
# Day11.Day11_first_half()
# Day12.Day12_first_half()
Day12.Day12_second_half()